### ISSUE TITLE
Shinden problem z prawie kazdym zaglebieniem

### ISSUE THREAD

**Issue by anon2018** [Lantash77/lantash-repo#27]
jest problem z shinden, nie dziala prawie kazda zaglebienie poza esezony, sprawdzane na czystym kodi  ( android i PC)sama wtyczka na wersji 20 i 21, z vpn bez vpn, hasla i loginy sa poprawne

dodaje log
`
2024-10-25 16:30:56.715 T:5184     info <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2024-10-25 16:31:17.703 T:5184    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-10-25 16:31:17.913 T:12716 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:18.319 T:5184     info <general>: Skipped 5 duplicate messages..
2024-10-25 16:31:18.319 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:18.319 T:3024  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:19.343 T:5184     info <general>: Skipped 2 duplicate messages..
2024-10-25 16:31:19.343 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:19.343 T:15724 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:20.493 T:5184     info <general>: Skipped 5 duplicate messages..
2024-10-25 16:31:20.493 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:21.426 T:1672  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:22.435 T:1672     info <general>: Skipped 2 duplicate messages..
2024-10-25 16:31:22.435 T:1672    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi 211\portable_data\addons\plugin.video.animeotaku\main.py", line 325, in <module>
                                                       mode_check()
                                                     File "D:\Kodi 211\portable_data\addons\plugin.video.animeotaku\main.py", line 221, in mode_check
                                                       hostanimeshinden.ListTitles()
                                                     File "D:\Kodi 211\portable_data\addons\plugin.video.animeotaku\hosts\hostanimeshinden.py", line 201, in ListTitles
                                                       link = BASE_URL + re.sub('/series/', 'series/', parseDOM(item, 'a', ret='href')[1])
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2024-10-25 16:31:22.451 T:8072    error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.animeotaku/?data=%7b%27fanart%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2ffanart.jpg%27%2c%20%27section%27%3a%20%27Aired%27%2c%20%27poster%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fsearch.png%27%2c%20%27thumb%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fsearch.png%27%7d&fanart&img&mode=SHListTitles&name=%5bAnime%5d%20Emitowane&page&poster&section&subdir&url=https%3a%2f%2fshinden.pl%2fseries%3fseries_status%5b0%5d%3dCurrently%2bAiring
2024-10-25 16:31:22.458 T:5184    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.animeotaku/?data=%7b%27fanart%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2ffanart.jpg%27%2c%20%27section%27%3a%20%27Aired%27%2c%20%27poster%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fsearch.png%27%2c%20%27thumb%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fsearch.png%27%7d&fanart&img&mode=SHListTitles&name=%5bAnime%5d%20Emitowane&page&poster&section&subdir&url=https%3a%2f%2fshinden.pl%2fseries%3fseries_status%5b0%5d%3dCurrently%2bAiring) failed
2024-10-25 16:31:22.644 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:22.644 T:9800  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:25.179 T:5184     info <general>: Skipped 5 duplicate messages..
2024-10-25 16:31:25.179 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:25.571 T:7740  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:27.060 T:5184     info <general>: Skipped 46 duplicate messages..
2024-10-25 16:31:27.060 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:27.276 T:11276 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:28.785 T:5184     info <general>: Skipped 84 duplicate messages..
2024-10-25 16:31:28.784 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:29.035 T:7060  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:30.648 T:5184     info <general>: Skipped 81 duplicate messages..
2024-10-25 16:31:30.648 T:5184     info <general>: Loading controller layout: D:\Kodi 211\addons\game.controller.keyboard\resources\layout.xml
2024-10-25 16:31:30.852 T:11288   error <general>: Unable to find plugin 
2024-10-25 16:31:30.852 T:11288   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://
2024-10-25 16:31:30.853 T:5184    error <general>: CGUIMediaWindow::GetDirectory(plugin://) failed
2024-10-25 16:31:31.125 T:5184  warning <general>: Repository add-on repository.EzzerMacsWizard uses plain HTTP for add-on downloads in path http://www.ezzer-mac.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.125 T:5184  warning <general>: Repository add-on repository.Fido uses plain HTTP for add-on downloads in path http://fantazyrepo.uk/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.125 T:5184  warning <general>: Repository add-on repository.NarcacistWizard uses plain HTTP for add-on downloads in path http://narcacist.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.125 T:5184  warning <general>: Repository add-on repository.Rising.Tides uses plain HTTP for add-on downloads in path http://mullafabz.xyz/Plugins/K19/Plugins/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.125 T:5184  warning <general>: Repository add-on repository.Wherethemonsterslive uses plain HTTP for add-on downloads in path http://www.midian.appboxes.co/wolfyB/files/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.126 T:5184     info <general>: Skipped 1 duplicate messages..
2024-10-25 16:31:31.126 T:5184  warning <general>: Repository add-on repository.djaythemes uses plain HTTP for add-on downloads in path http://djaythemes.xyz/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.126 T:5184  warning <general>: Repository add-on repository.funstersplace uses plain HTTP for add-on downloads in path http://funstersplace.net/19repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.126 T:5184  warning <general>: Repository add-on repository.grindhousekodi uses plain HTTP for add-on downloads in path http://grindhousekodi.us/grindhouse/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.126 T:5184  warning <general>: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom.kote.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.126 T:5184  warning <general>: Repository add-on repository.twistednutz uses plain HTTP for add-on downloads in path http://twistednutz.xyz/twisted/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.EzzerMacsWizard uses plain HTTP for add-on downloads in path http://www.ezzer-mac.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.Fido uses plain HTTP for add-on downloads in path http://fantazyrepo.uk/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.NarcacistWizard uses plain HTTP for add-on downloads in path http://narcacist.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.Rising.Tides uses plain HTTP for add-on downloads in path http://mullafabz.xyz/Plugins/K19/Plugins/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.Wherethemonsterslive uses plain HTTP for add-on downloads in path http://www.midian.appboxes.co/wolfyB/files/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404    info <general>: Skipped 1 duplicate messages..
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.djaythemes uses plain HTTP for add-on downloads in path http://djaythemes.xyz/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.funstersplace uses plain HTTP for add-on downloads in path http://funstersplace.net/19repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.grindhousekodi uses plain HTTP for add-on downloads in path http://grindhousekodi.us/grindhouse/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom.kote.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.486 T:17404 warning <general>: Repository add-on repository.twistednutz uses plain HTTP for add-on downloads in path http://twistednutz.xyz/twisted/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.EzzerMacsWizard uses plain HTTP for add-on downloads in path http://www.ezzer-mac.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.Fido uses plain HTTP for add-on downloads in path http://fantazyrepo.uk/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.NarcacistWizard uses plain HTTP for add-on downloads in path http://narcacist.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.Rising.Tides uses plain HTTP for add-on downloads in path http://mullafabz.xyz/Plugins/K19/Plugins/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.Wherethemonsterslive uses plain HTTP for add-on downloads in path http://www.midian.appboxes.co/wolfyB/files/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252    info <general>: Skipped 1 duplicate messages..
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.djaythemes uses plain HTTP for add-on downloads in path http://djaythemes.xyz/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.funstersplace uses plain HTTP for add-on downloads in path http://funstersplace.net/19repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.788 T:10252 warning <general>: Repository add-on repository.grindhousekodi uses plain HTTP for add-on downloads in path http://grindhousekodi.us/grindhouse/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.789 T:10252 warning <general>: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom.kote.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:31.789 T:10252 warning <general>: Repository add-on repository.twistednutz uses plain HTTP for add-on downloads in path http://twistednutz.xyz/twisted/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.256 T:9136  warning <general>: Repository add-on repository.EzzerMacsWizard uses plain HTTP for add-on downloads in path http://www.ezzer-mac.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.256 T:9136  warning <general>: Repository add-on repository.Fido uses plain HTTP for add-on downloads in path http://fantazyrepo.uk/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.256 T:9136  warning <general>: Repository add-on repository.NarcacistWizard uses plain HTTP for add-on downloads in path http://narcacist.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.256 T:9136  warning <general>: Repository add-on repository.Rising.Tides uses plain HTTP for add-on downloads in path http://mullafabz.xyz/Plugins/K19/Plugins/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.256 T:9136  warning <general>: Repository add-on repository.Wherethemonsterslive uses plain HTTP for add-on downloads in path http://www.midian.appboxes.co/wolfyB/files/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.256 T:9136     info <general>: Skipped 1 duplicate messages..
2024-10-25 16:31:33.256 T:9136  warning <general>: Repository add-on repository.djaythemes uses plain HTTP for add-on downloads in path http://djaythemes.xyz/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.257 T:9136  warning <general>: Repository add-on repository.funstersplace uses plain HTTP for add-on downloads in path http://funstersplace.net/19repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.257 T:9136  warning <general>: Repository add-on repository.grindhousekodi uses plain HTTP for add-on downloads in path http://grindhousekodi.us/grindhouse/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.257 T:9136  warning <general>: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom.kote.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:33.257 T:9136  warning <general>: Repository add-on repository.twistednutz uses plain HTTP for add-on downloads in path http://twistednutz.xyz/twisted/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.416 T:16316 warning <general>: Repository add-on repository.EzzerMacsWizard uses plain HTTP for add-on downloads in path http://www.ezzer-mac.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.416 T:16316 warning <general>: Repository add-on repository.Fido uses plain HTTP for add-on downloads in path http://fantazyrepo.uk/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.416 T:16316 warning <general>: Repository add-on repository.NarcacistWizard uses plain HTTP for add-on downloads in path http://narcacist.com/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.416 T:16316 warning <general>: Repository add-on repository.Rising.Tides uses plain HTTP for add-on downloads in path http://mullafabz.xyz/Plugins/K19/Plugins/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.416 T:16316 warning <general>: Repository add-on repository.Wherethemonsterslive uses plain HTTP for add-on downloads in path http://www.midian.appboxes.co/wolfyB/files/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.416 T:16316    info <general>: Skipped 1 duplicate messages..
2024-10-25 16:31:34.416 T:16316 warning <general>: Repository add-on repository.djaythemes uses plain HTTP for add-on downloads in path http://djaythemes.xyz/_repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.416 T:16316 warning <general>: Repository add-on repository.funstersplace uses plain HTTP for add-on downloads in path http://funstersplace.net/19repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.417 T:16316 warning <general>: Repository add-on repository.grindhousekodi uses plain HTTP for add-on downloads in path http://grindhousekodi.us/grindhouse/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.417 T:16316 warning <general>: Repository add-on repository.phantom uses plain HTTP for add-on downloads in path http://phantom.kote.pl/repo/prod/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:34.417 T:16316 warning <general>: Repository add-on repository.twistednutz uses plain HTTP for add-on downloads in path http://twistednutz.xyz/twisted/repo/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
2024-10-25 16:31:36.483 T:5184    error <general>: Control 55 in window 10025 has been asked to focus, but it can't
2024-10-25 16:31:36.702 T:14768 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:37.098 T:5184     info <general>: Skipped 6 duplicate messages..
2024-10-25 16:31:37.098 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:37.099 T:6748  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:38.116 T:5184     info <general>: Skipped 1 duplicate messages..
2024-10-25 16:31:38.116 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:38.116 T:10752 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:42.857 T:5184     info <general>: Skipped 5 duplicate messages..
2024-10-25 16:31:42.857 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:43.381 T:7012  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:45.149 T:5184     info <general>: Skipped 26 duplicate messages..
2024-10-25 16:31:45.149 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:31:45.958 T:9188  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:31:56.659 T:5184     info <general>: Skipped 10 duplicate messages..
2024-10-25 16:31:56.659 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:32:01.326 T:12048   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "D:\Kodi 211\portable_data\addons\plugin.video.animeotaku\main.py", line 325, in <module>
                                                       mode_check()
                                                     File "D:\Kodi 211\portable_data\addons\plugin.video.animeotaku\main.py", line 237, in mode_check
                                                       hostanimeshinden.ListEpisodes()
                                                     File "D:\Kodi 211\portable_data\addons\plugin.video.animeotaku\hosts\hostanimeshinden.py", line 318, in ListEpisodes
                                                       result = parseDOM(html, 'tbody', {'class': 'list-episode-checkboxes'})[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2024-10-25 16:32:01.348 T:21192   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.animeotaku/?data=%7b%27poster%27%3a%20%27https%3a%2f%2fshinden.pl%2f%2fseries%2f45085-ansatsu-kyoushitsu-tv-2nd-season%27%2c%20%27thumb%27%3a%20%27https%3a%2f%2fshinden.pl%2f%2fseries%2f45085-ansatsu-kyoushitsu-tv-2nd-season%27%2c%20%27fanart%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fsunset.jpg%27%2c%20%27subdir%27%3a%20%27Akcja%27%2c%20%27plot%27%3a%20%27%27%2c%20%27genre%27%3a%20%5b%5d%2c%20%27year%27%3a%200%2c%20%27section%27%3a%20%27episodes%27%7d&fanart&img&mode=SHListEpisodes&name=Akcja&page&poster&section&subdir&url=https%3a%2f%2fshinden.pl%2f%2fgenre%2f5-action
2024-10-25 16:32:01.349 T:5184    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.animeotaku/?data=%7b%27poster%27%3a%20%27https%3a%2f%2fshinden.pl%2f%2fseries%2f45085-ansatsu-kyoushitsu-tv-2nd-season%27%2c%20%27thumb%27%3a%20%27https%3a%2f%2fshinden.pl%2f%2fseries%2f45085-ansatsu-kyoushitsu-tv-2nd-season%27%2c%20%27fanart%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fsunset.jpg%27%2c%20%27subdir%27%3a%20%27Akcja%27%2c%20%27plot%27%3a%20%27%27%2c%20%27genre%27%3a%20%5b%5d%2c%20%27year%27%3a%200%2c%20%27section%27%3a%20%27episodes%27%7d&fanart&img&mode=SHListEpisodes&name=Akcja&page&poster&section&subdir&url=https%3a%2f%2fshinden.pl%2f%2fgenre%2f5-action) failed
2024-10-25 16:32:02.846 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:32:03.205 T:19932 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:32:04.340 T:5184     info <general>: Skipped 32 duplicate messages..
2024-10-25 16:32:04.340 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:32:04.474 T:19844 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:32:15.950 T:14008    info <general>: Skipped 9 duplicate messages..
2024-10-25 16:32:15.950 T:14008 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:32:40.971 T:13560    info <general>: Skipped 11 duplicate messages..
2024-10-25 16:32:40.971 T:13560 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:32:41.377 T:5184     info <general>: Skipped 2 duplicate messages..
2024-10-25 16:32:41.377 T:5184  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2024-10-25 16:32:42.817 T:5184     info <general>: Stopping the application...
2024-10-25 16:32:42.817 T:5184     info <general>: Stopping player
2024-10-25 16:32:42.817 T:5184     info <general>: Storing total System Uptime
2024-10-25 16:32:42.817 T:5184     info <general>: Saving settings
2024-10-25 16:32:42.820 T:5184     info <general>: Saving skin settings
2024-10-25 16:32:42.820 T:5184     info <general>: Stopping all
2024-10-25 16:32:42.821 T:5184     info <general>: ES: Stopping event server
2024-10-25 16:32:42.821 T:5184     info <general>: [WS-Discovery]: terminating
2024-10-25 16:32:42.978 T:19780    info <general>: ES: UDP Event server stopped
2024-10-25 16:32:42.979 T:5184     info <general>: CServiceAddonManager: failed to stop service.xbmc.versioncheck (may have ended)
2024-10-25 16:32:47.984 T:5184    error <general>: CPythonInvoker(33, D:\Kodi 211\portable_data\addons\plugin.video.animeotaku\main.py): script didn't stop in 5 seconds - let's kill it
2024-10-25 16:32:48.003 T:5184     info <general>: Application stopped
2024-10-25 16:32:48.204 T:2240  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-10-25 16:32:48.228 T:10900    info <general>: Skipped 1 duplicate messages..
2024-10-25 16:32:48.228 T:10900   error <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.animeotaku/?data=%7b%27poster%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fletters%2fA.png%27%2c%20%27thumb%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fletters%2fA.png%27%2c%20%27fanart%27%3a%20%27D%3a%5c%5cKodi%20211%5c%5cportable_data%5c%5caddons%5c%5cplugin.video.animeotaku%5c%5cresources%2fmedia%2fsunset.jpg%27%2c%20%27section%27%3a%20%27A%27%7d&fanart&img&mode=SHListTitles&name=A&page&poster&section&subdir&url=https%3a%2f%2fshinden.pl%2fseries%3fletter%3dA%26page%3d1
2024-10-25 16:32:48.707 T:2240  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
`

**Comment by Lantash77** [comment]
Poszedł fix do shinden - dodatkowo wyłączone wbijam.pl
